export default function generateCaption(body, credit) {
    const hashtag = hashtags[Math.floor(Math.random() * hashtags.length)];
    const caption = `
${body}
▪️⠀⁠
▪️⠀⁠
👉 Follow @calisthenicxelite  👈⠀⁠
👉 Follow @calisthenicxelite  👈  ⠀⁠
▪️⠀⁠
▪️⠀⁠
▪️⠀⁠
🎥 @${credit}
▪️⠀⁠
▪️⠀⁠
▪️⠀⁠
${hashtag}`;
    return caption;
}

const hashtags = `#physicalconditioning #barsquad #barsteel #calisthenicsworldwide #streetworkoutmalaysia #muscledefinition #repsandsets #barworkout #thenx #barsparta #calisthenicsvideos #musclevideos #workout24 #fitnessvideos #calisthenicsworkout #bodyweight #calisthenics #workoutmotivation #nopainnogain #beastmode #frontlever #planche #dips #pullups #muscleup
#physicalconditioning #barsquad #barsteel #calisthenicsworldwide #streetworkoutmalaysia #theshowoffz #handstanding #coupleworkout #calisthenicstraining #musclevideos #madbarz #calisthenic #workout24 #calisthenicsmovement #calisthenicsworkout #bodyweight #calisthenics #workoutmotivation #nopainnogain #beastmode #frontlever #planche #dips #pullups #muscleup
#physicalconditioning #barsquad #barsteel #calisthenicsworldwide #streetworkoutmalaysia #muscledefinition #repsandsets #barworkout #thenx #barsparta #madbarz #calisthenic #workout24 #calisthenicsmovement #calisthenicsworkout #bodyweight #calisthenics #workoutmotivation #nopainnogain #beastmode #frontlever #planche #dips #pullups #muscleup
#power #legday #couplegoals #sweat #cardio #tumbling #parkour #barbrothers #streetworkout #grindout #fullplanche #handstandpushups #legsworkout #handstand365 #fitnessvideos #handstanding #calisthenicsaroundtheworld #streetworkouts #barbars #calisthenicstraining #progressivecalisthenics #becurefit #squatchallange #planches #calisthenia
#gymnastics #gym #personaltrainer #gymlife #trainhard #functionalfitness #bodyweighttraining #barstarzz #functionaltraining #muscleup #chinup #handstandpractice #humanflag #chinups #legsworkout #calisthenicsaroundtheworld #stickit #dragonflag #streetworkoutpro #streetworkouts #physicalconditioning #muscledefinition #calisthenicsfreestyle #calisthenicsuk #workoutmemes
#focus #personaltrainer #bodybuilder #beastmode #gym #chestworkout #flips #workoutroutine #parkour #legworkout #squatchallenge #fullplanche #bodyweightworkout #thenx #workout24 #streetworkouts #dragonflag #calisthenicsaroundtheworld #stickit #streetworkoutpro #calisthenicsgirl #streetworkoutmalaysia #physicalconditioning #theshowoffz #workoutmeme
#strong #lifestyle #dedication #nopainnogain #bodybuilding #streetworkout #functionalfitness #grindout #frontlever #fitmalaysia #excersise #barsparta #madbarz #pushupchallenge #powermoves #barbars #streetworkouts #straddleplanche #workoutroutines #gorillagang #muscledefinition #streetlifting #humanflagtraining #calisthenia #calisthenicsfreestyle
#personaltrainer #bodybuilder #noexcuses #sweat #lifestyle #chestworkout #tumbling #workoutoftheday #functionaltraining #workoutroutine #handstandpractice #madbarz #chinups #pistolsquat #squatchallenge #barbars #repsandsets #dragonflag #straddleplanche #coupleworkout #weightedcalisthenics #streetworkoutmalaysia #calisthenicsvideos #theshowoffz #tuckedplanche
#bodybuilding #motivation #ripped #instafitness #dedication #workoutroutine #parkour #athletes #fitmotivation #dips #pistolsquat #letsgetstarted #muscleups #squatchallenge #calisthenicsmovement #straddleplanche #dragonflag #repsandsets #stickit #barathlete #theshowoffz #calisthenics_athletes #progressivecalisthenics #chestandtriceps #tuckedplanche
#shredded #dedication #power #strength #cardio #handstand #functionalfitness #pullups #cult #frontlever #powermoves #acrobats #chinups #workout24 #legsworkout #calisthenicstraining #handstanding #dragonflag #stickit #repsandsets #theshowoffz #becurefit #calisthenicsvideos #calisthenicsfreestyle #workoutmemes
#workoutmotivation #strong #bar #nopainnogain #personaltrainer #fitmotivation #planche #handstand #dancefitness #movement #excersise #handstand365 #calisthenicsgirls #fitnessvideos #calisthenicsmovement #barathlete #calisthenicsaroundtheworld #streetworkoutpro #barbars #repsandsets #progressivecalisthenics #barragazz #gymmotivations #insaneworkout #chestandtriceps
#gainz #bodybuilder #gym #sweat #gymmotivation #movement #calisthenics #legworkout #chestworkout #frontlever #calisthenicsworkout #pushupchallenge #excersise #powermoves #backlever #gorillagang #dragonflag #straddleplanche #calisthenicstraining #repsandsets #calisthenicsgirl #calisthenics_athletes #tuckedplanche #chestandtriceps #weightedcalisthenics
#trainhard #bodybuilder #flex #squats #instafit #tumbling #cult #streetworkout #pushpullgrind #legworkout #workout24 #muscleups #powermoves #letsgetstarted #imuscleup #streetworkoutpro #straddleplanche #streetworkouts #stickit #calisthenicsaroundtheworld #calisthenicsgirl #calisthenicsuk #streetlifting #barragazz #streetworkoutmalaysia
#squat #strength #bodybuilder #beastmode #fit #barbrothers #calisthenics #pushpullgrind #cult #functionalfitness #fitnessvideos #imuscleup #muscleups #calisthenicsmovement #antigravity #straddleplanche #workoutroutines #coupleworkout #streetworkoutpro #dragonflag #calisthenia #streetlifting #calisthenicsgirl #barsteel #pushupsfordays
#instafitness #legday #fitness #gainz #muscle #streetworkout #flips #fitmotivation #fitnessgear #chestworkout #handstand365 #fullplanche #fitnessvideos #baristiworkout #pushupchallenge #coupleworkout #repsandsets #handstanding #straddleplanche #antigravityfitness #gymmotivations #insaneworkout #barsteel #progressivecalisthenics #tuckedplanche
#trainhard #sweat #beastmode #legday #workout #parkour #athletes #movement #pullups #calistenia #shreddedunion #lsit #transformationchallenge #humanflag #calisthenicsmovement #streetworkouts #handstanding #straddleplanche #streetworkoutpro #barbars #calisthenics_athletes #pushupsfordays #tuckedplanche #insaneworkout #humanflagtraining
#sweat #gymmotivation #flex #bodybuilding #strength #fitmotivation #grow #handstands #traininsane #fitnessgear #fitnessvideos #excersise #lsit #powermoves #handstandpushups #coupleworkout #calisthenicsaroundtheworld #workoutroutines #stickit #handstanding #barragazz #squatchallange #workoutmemes #calisthenicsuk #calisthenicsvideos
#workout #grind #lifestyle #sweat #squats #dancefitness #streetworkout #handstand #fitmalaysia #envywear #backlever #muscleups #acrobats #chinups #powermoves #coupleworkout #handstanding #dragonflag #antigravityfitness #stickit #weightedcalisthenics #calisthenics_best #barsteel #barragazz #calisthenics_athletes
#workout #flex #power #bodybuilder #noexcuses #grindout #fitmotivation #movement #functionaltraining #dancefitness #madbarz #squatchallenge #shreddedunion #imuscleup #acrobats #straddleplanche #antigravityfitness #coupleworkout #barathlete #barbars #calisthenicsworldwide #insaneworkout #barsquad #tuckedplanche #theshowoffz
#squats #workout #sweat #gymnastics #freestyle #envywear #streetworkout #chestworkout #grindout #excercise #fitnessvideos #pistolsquat #excersise #calisthenicsmovement #musclevideos #straddleplanche #stickit #dragonflag #calisthenicsaroundtheworld #workoutroutines #insaneworkout #calisthenics_best #barsquad #gymmotivations #becurefit
#instafitness #bodybuilding #trainhard #muscle #gym #traininsane #workoutroutine #planche #barbrothers #tumbling #backlever #acrobats #barsparta #barworkout #baristi #repsandsets #dragonflag #gorillagang #coupleworkout #streetworkouts #pistolsquats #calisthenics_best #barragazz #planches #progressivecalisthenics
#meme #strong #gym #ripped #fit #athletes #legworkout #excercise #fitnessgear #calisthenics #lsit #calisthenicsmovement #excersise #workout24 #backlever #gorillagang #repsandsets #stickit #straddleplanche #coupleworkout #tuckedplanche #insaneworkout #barsteel #calisthenics_athletes #physicalconditioning
#workoutmotivation #beastmode #personaltrainer #abs #flex #streetworkout #handstand #tumbling #barbrothers #calisthenics #workout24 #barsparta #handstandpushups #madbarz #calisthenicsworkout #repsandsets #streetworkouts #streetworkoutpro #calisthenicstraining #barbars #pushupsfordays #squatchallange #weightedcalisthenics #gymmotivations #calisthenics_athletes
#dedication #bodybuilder #gym #eatclean #fitness #chestworkout #streetworkout #fitmotivation #envywear #handstands #pushupchallenge #chinup #squatchallenge #fitnessvideos #barsparta #gorillagang #coupleworkout #stickit #handstanding #barbars #calisthenia #muscledefinition #workoutmemes #streetworkoutmalaysia #calisthenicsuk
#power #fit #eatclean #squat #gym #envywear #workoutroutine #dips #flips #grow #chinup #madbarz #letsgetstarted #acrobats #shreddedunion #workoutroutines #straddleplanche #barathlete #handstanding #streetworkouts #barragazz #progressivecalisthenics #pushupsfordays #barsquad #workoutmemes
#noexcuses #abs #strength #grind #workout #handstands #excercise #barstarzz #calistenia #functionalfitness #thenx #imuscleup #acrobats #squatting #antigravity #workoutroutines #calisthenicsaroundtheworld #straddleplanche #coupleworkout #streetworkouts #workoutmeme #workoutmemes #insaneworkout #calisthenicsvideos #calisthenicsworldwide
#squats #workoutmotivation #beastmode #gym #trainhard #bodyweighttraining #legworkout #movement #pushpullgrind #fitmotivation #fitnessvideos #handstand365 #legsworkout #fullplanche #letsgetstarted #gorillagang #barathlete #barbars #coupleworkout #handstanding #becurefit #calisthenicsfreestyle #gymmotivations #calisthenicsuk #muscledefinition
#motivation #gymnastics #muscle #workout #legday #flips #traininsane #calistenia #dancefitness #fitnessinspiration #backlever #excersise #muscleups #barsparta #calisthenic #streetworkouts #straddleplanche #calisthenicstraining #workoutroutines #barathlete #calisthenicsworldwide #insaneworkout #planches #pistolsquats #vsit
#couplegoals #sweat #gainz #grind #muscle #functionalfitness #barbrothers #envywear #fitmalaysia #tumbling #thenx #squatchallenge #squatting #calisthenicsworkout #humanflag #calisthenicsaroundtheworld #barathlete #streetworkoutpro #workoutroutines #antigravityfitness #planches #barragazz #calisthenicsworldwide #streetlifting #calisthenicsvideos
#freestyle #abs #shredded #trainhard #fitness #grindout #flips #barstarzz #functionalfitness #tumbling #calisthenicsmovement #calisthenic #humanflag #letsgetstarted #chinup #dragonflag #streetworkoutpro #barbars #calisthenicsaroundtheworld #handstanding #barragazz #pistolsquats #humanflagtraining #streetlifting #insaneworkout
#nopainnogain #beastmode #gainz #noexcuses #bar #barstarzz #dancefitness #envywear #workoutroutine #fitmotivation #calisthenicsworkout #musclevideos #acrobats #lsit #madbarz #calisthenicsaroundtheworld #dragonflag #antigravityfitness #streetworkoutpro #gorillagang #insaneworkout #calisthenics_best #calisthenicsvideos #pushupsfordays #calisthenics_athletes
#eatclean #squat #grind #bodybuilder #cardio #streetworkout #tumbling #handstand #functionaltraining #pullups #legsworkout #muscleups #antigravity #imuscleup #thenx #barathlete #handstanding #antigravityfitness #streetworkoutpro #calisthenicsaroundtheworld #pushupsfordays #workoutmemes #calisthenics_athletes #barragazz #pistolsquats
#fitness #flex #eatclean #gymmotivation #muscle #flips #excercise #tumbling #movement #pushpullgrind #workout24 #squatting #baristi #fullplanche #lsit #workoutroutines #barathlete #dragonflag #antigravityfitness #coupleworkout #barragazz #streetworkoutmalaysia #chestandtriceps #streetlifting #becurefit
#gainz #couplegoals #fit #bodybuilding #abs #pullups #fitnessgear #frontlever #calisthenics #fitnessinspiration #shreddedunion #antigravity #barworkout #handstandpractice #barsparta #repsandsets #dragonflag #calisthenicsaroundtheworld #stickit #barbars #barragazz #tuckedplanche #vsit #calisthenicsvideos #calisthenicsworldwide
#grind #focus #freestyle #fit #ripped #functionalfitness #legworkout #dancefitness #grow #flips #chinup #lsit #barsparta #thenx #acrobats #barathlete #barbars #calisthenicstraining #stickit #straddleplanche #humanflagtraining #pistolsquats #muscledefinition #progressivecalisthenics #calisthenicsfreestyle
#squats #bar #squat #lifestyle #sweat #dancefitness #athletes #cult #parkour #dips #transformationchallenge #calisthenicsworkout #pistolsquat #handstandpushups #calisthenicsmovement #antigravityfitness #streetworkouts #coupleworkout #stickit #barbars #gymmotivations #barsteel #calisthenia #calisthenicsuk #squatchallange
#gymnastics #flex #workoutmotivation #meme #sweat #barbrothers #grindout #fitmalaysia #athletes #calisthenics #antigravity #calisthenicsmovement #fullplanche #shreddedunion #pushupchallenge #streetworkoutpro #repsandsets #barathlete #dragonflag #coupleworkout #calisthenicsfreestyle #calisthenics_best #planches #calisthenics_athletes #pushupsfordays
#couplegoals #beastmode #meme #squats #bar #flips #muscleup #bodyweight #fitmalaysia #workoutroutine #baristi #imuscleup #legsworkout #fitnessvideos #humanflag #workoutroutines #streetworkouts #calisthenicsaroundtheworld #calisthenicstraining #barbars #vsit #barsquad #squatchallange #physicalconditioning #calisthenicsuk
#lifestyle #gymmotivation #grind #workoutmotivation #strong #fitmotivation #calisthenics #chestworkout #muscleup #handstands #fullplanche #antigravity #fitnessvideos #squatting #calisthenic #coupleworkout #straddleplanche #stickit #barathlete #streetworkouts #physicalconditioning #calisthenics_best #planches #streetworkoutmalaysia #insaneworkout
#strength #couplegoals #personaltrainer #freestyle #squat #legworkout #bodyweighttraining #streetworkout #barbrothers #functionaltraining #imuscleup #letsgetstarted #legsworkout #baristi #handstandpushups #dragonflag #antigravityfitness #stickit #barbars #handstanding #squatchallange #calisthenics_athletes #calisthenicsworldwide #calisthenicsuk #muscledefinition
#strong #gym #cardio #power #strength #barstarzz #athletes #pullup #bodyweighttraining #envywear #muscleups #transformationchallenge #thenx #squatting #barsparta #stickit #coupleworkout #antigravityfitness #calisthenicstraining #streetworkouts #calisthenicsworldwide #pushupsfordays #barsquad #workoutmeme #becurefit
#sweat #flex #personaltrainer #bodybuilding #motivation #calisthenics #frontlever #pushpullgrind #flips #barbrothers #handstandpractice #shreddedunion #barsparta #chinups #madbarz #streetworkoutpro #repsandsets #coupleworkout #gorillagang #calisthenicstraining #squatchallange #tuckedplanche #calisthenicsfreestyle #vsit #calisthenics_athletes
#strength #muscle #motivation #legday #bodybuilder #bodyweighttraining #barbrothers #chestworkout #excercise #streetworkout #handstandpushups #antigravity #humanflag #muscleups #lsit #stickit #repsandsets #handstanding #calisthenicstraining #dragonflag #humanflagtraining #theshowoffz #barsteel #vsit #streetlifting
#grind #gymmotivation #lifestyle #strong #ripped #parkour #pullups #barstarzz #frontlever #tumbling #workout24 #muscleups #squatchallenge #calisthenicsmovement #lsit #gorillagang #calisthenicstraining #workoutroutines #barathlete #barbars #calisthenicsuk #humanflagtraining #barsteel #pushupsfordays #muscledefinition
#fitness #fit #power #abs #sweat #grindout #traininsane #chestworkout #movement #workoutoftheday #humanflag #imuscleup #fitnessvideos #fitnessvideos #shreddedunion #calisthenicsaroundtheworld #streetworkoutpro #dragonflag #repsandsets #barbars #barragazz #planches #vsit #tuckedplanche #becurefit
#bodybuilder #gymnastics #cardio #personaltrainer #instafit #calistenia #flips #fitnessgear #handstands #handstand #fitnessvideos #barsparta #barworkout #muscleups #antigravity #barbars #handstanding #gorillagang #dragonflag #repsandsets #calisthenics_athletes #workoutmeme #becurefit #tuckedplanche #squatchallange
#gymmotivation #gymnastics #couplegoals #workoutmotivation #ripped #bodyweight #calisthenics #fitmotivation #barstarzz #fitmalaysia #muscleups #handstandpushups #imuscleup #baristiworkout #squatchallenge #repsandsets #streetworkoutpro #dragonflag #straddleplanche #calisthenicstraining #theshowoffz #insaneworkout #chestandtriceps #planches #squatchallange
#dedication #fitness #gym #beastmode #noexcuses #bodyweight #athletes #flips #barbrothers #workoutroutine #thenx #acrobats #musclevideos #lsit #backlever #repsandsets #antigravityfitness #streetworkoutpro #barathlete #workoutroutines #calisthenicsgirl #squatchallange #humanflagtraining #pushupsfordays #streetlifting
#flex #focus #squats #strength #power #calistenia #workoutroutine #dancefitness #pullups #workoutoftheday #bodyweightworkout #barworkout #letsgetstarted #calisthenicsmovement #legsworkout #barathlete #calisthenicstraining #gorillagang #streetworkoutpro #repsandsets #theshowoffz #chestandtriceps #workoutmeme #calisthenicsfreestyle #squatchallange
#gymnastics #personaltrainer #cardio #bodybuilder #fitness #handstand #fitmotivation #parkour #dips #fitnessgear #letsgetstarted #chinup #fitnessvideos #chinups #pushupchallenge #barbars #repsandsets #workoutroutines #straddleplanche #stickit #chestandtriceps #barsteel #physicalconditioning #squatchallange #insaneworkout
#bodybuilder #gymnastics #strength #ripped #eatclean #handstand #bodyweight #fitmotivation #bodyweighttraining #fitmalaysia #muscleups #handstandpushups #lsit #powermoves #baristiworkout #dragonflag #gorillagang #barathlete #handstanding #repsandsets #humanflagtraining #streetlifting #workoutmeme #calisthenicsworldwide #pushupsfordays
#strong #workoutmotivation #fit #power #couplegoals #parkour #flips #envywear #barstarzz #handstand #imuscleup #calisthenicsgirls #pushupchallenge #backlever #squatchallenge #coupleworkout #repsandsets #barbars #straddleplanche #calisthenicstraining #theshowoffz #progressivecalisthenics #barsteel #muscledefinition #weightedcalisthenics
#fitness #gymlife #sweat #instafitness #lifestyle #handstands #functionaltraining #envywear #streetworkout #pullup #calisthenic #fullplanche #lsit #squatting #acrobats #antigravityfitness #straddleplanche #barathlete #streetworkouts #coupleworkout #tuckedplanche #workoutmemes #calisthenics_athletes #insaneworkout #calisthenicsworldwide`.split('\n');